### ISSUE TITLE
Mac Sonoma: App does not run due to new security setting

### ISSUE THREAD

**Issue by mikaelho** [benjie-git/CardStock#12]
After installing `pip install cardstock`, trying to run `cardstock` in terminal results in this message:
`Python[61225:7000989] WARNING: Secure coding is not enabled for restorable state! Enable secure coding by implementing NSApplicationDelegate.applicationSupportsSecureRestorableState: and returning YES.`

Have not looked deeper, but seems to be a recent issue caused by the latest MacOS update. Could not find a related issue reported for wxPython (yet?).

**Comment by benjie-git** [comment]
Thanks!  Does cardstock still seem to run ok anyway?  Or is this breaking the app?

**Comment by mikaelho** [comment]
App does not start, only the error shown in terminal and OS reports that Python has stopped unexpectedly.

**Comment by benjie-git** [comment]
Thanks.  I'm guessing this is a PyInstaller bug.  I don't have a machine running Sonoma currently, but I'll try to get this working soon.  In the meantime, you could try out my web-based cardstock tool: https://cardstock.run/

**Comment by benjie-git** [comment]
Could you test out the latest MacOS build from here:
    https://github.com/benjie-git/CardStock/releases/tag/v0.99.4
and let me know if it works for you?  It works for me on Intel Sonoma.  Thanks!

**Comment by mikaelho** [comment]
Thanks. I am on Mac M1, but the issue is probably the Python 3.12 I was using. Looks like you have blocked 3.12 from the supported versions now, so will take me a little more time to set 3.11 up and test.

**Comment by mikaelho** [comment]
Tried the basic `pip install cardstock` with Python 3.11, and it works fine.
