### ISSUE TITLE
FEATURE REQUEST: Color picker

### ISSUE THREAD

**Issue by everythingability** [benjie-git/CardStock#21]
Hi,

when you are setting say the fill color of a rect, the result of your choice is only shown after you have closed the windoid.

I'd much prefer it if it updated on every mouseup... so I can preview what pink looks like with 50% opacity say...

**Comment by benjie-git** [comment]
This works as described on the web version, but sadly the wxPython color picker does not tell me the current color until the user closes the picker.  I've tried a few workarounds, to no avail.
