### ISSUE TITLE
App does not do anything  when exporting to duplicate name

### ISSUE THREAD

**Issue by blingdahl** [benjie-git/CardStock#8]
Steps to reproduce:

1. Open CardStock_Designer.app
2. Open an example stack
3. File | Export Stack
4. Export as App
5. Save in Downloads
6. File | Export Stack
7. Save in Downloads

Expected:
Prompts for whether you want to overwrite

Actual:
Export does not do anything

**Comment by benjie-git** [comment]
fixed. now shows error messages instead of failing silently
